src/Entity/ShoppingList.php
<?php
// api/src/Entity/ShoppingList.php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
/**
 * A ShoppingList.
 *
 * @ORM\Entity
 * @ApiResource(attributes={"filters"={"ShoppingList.User"}})
 *     
 */
class ShoppingList
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column
     */
    public $title='';

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="shoppingLists")
     * @ORM\JoinColumn(nullable=false)
     */
    private $User;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ShoppingItem", mappedBy="shoppingList", orphanRemoval=true)
     * @ApiSubresource
     */
    private $ShoppingItems;

    
    public function __construct()
    {
        $this->ShoppingItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setTitle($title): self
    {
        $this->title=$title;
        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    /**
     * @return Collection|ShoppingItem[]
     */
    public function getShoppingItems(): Collection
    {
        return $this->ShoppingItems;
    }

    public function addShoppingItem(ShoppingItem $shoppingItem): self
    {
        if (!$this->ShoppingItems->contains($shoppingItem)) {
            $this->ShoppingItems[] = $shoppingItem;
            $shoppingItem->setShoppingList($this);
        }

        return $this;
    }

    public function removeShoppingItem(ShoppingItem $shoppingItem): self
    {
        if ($this->ShoppingItems->contains($shoppingItem)) {
            $this->ShoppingItems->removeElement($shoppingItem);
            // set the owning side to null (unless already changed)
            if ($shoppingItem->getShoppingList() === $this) {
                $shoppingItem->setShoppingList(null);
            }
        }

        return $this;
    }

}

src/Controller/DefaultController.php
<?php

namespace App\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class DefaultController extends AbstractController{

	/**
	 *@Route("/", name="index")
	 */
	public function index(){
		return $this->render('default/index.html.twig',
			["page_title" => "Index"]
		);
	}

	/**
	 *@Route("/app", name="app")
	 *
	 */
	public function app(){
		return $this->render('default/app.html.twig',
			["page_title" => "Index"]
		);
	}
}

templates/default/includes/footer.html.twig
	<footer>
		<script src="https://code.jquery.com/jquery-3.3.1.min.js" ></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"  crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js" crossorigin="anonymous"></script>
		
		<script>
{% if is_granted('IS_AUTHENTICATED_FULLY') %}			
	var lists = [];
	var lists_old= [];
	var user_bfr =  "/api/users/{{app.user.id}}"
	$( document ).ready(function() {
		$("#loader").show();
		$.get( "/api/users/{{app.user.id}}/shopping_lists", async function( data ) {
			for (var i = 0; i < data['hydra:member'].length; i++) {
				let l = data['hydra:member'][i]
				lists[lists.length] = l
		}
		lists_old = JSON.parse(JSON.stringify(lists))
		$("#loader").hide();

		let vm = new Vue({
			el: '#lists',
			data: {
				todos: lists,
				newTodoText:"New List"
			},			      
			methods: {
				reverseMessage: async function (id) {
					$("#loader").show();
					for (var i = 0; i < lists.length; i++) {
						if(lists[i]["id"] == id){
							if(lists[i]["ShoppingItems"] && 
								typeof lists[i]["ShoppingItems"][0] === "string")
							{
									for (var j = 0; j < lists[i]["ShoppingItems"].length; j++) {
										await $.get( lists[i]["ShoppingItems"][j], async function( d ) {
											let item = {}
											item["id"] = d["id"]
											item["checked"] = d["checked"]
											item["item"] = d["item"]
											item["shoppingList"] = d["shoppingList"]
											lists[i]["ShoppingItems"][j] = item

										});
								}
							}
							$("#loader").hide();
							$("#list").show();
							lists_vm.todo = lists[i]["ShoppingItems"]
							lists_vm.listid = i;
							lists_vm.shoppingList="/api/shopping_lists/"+lists[i]["id"]
							$("#lists").hide();
							break;
						}

					}
				},
				addNewTodo: function () {
					$.ajax({
					  url: '/api/shopping_lists',
					  type: 'POST',
					  contentType : "application/json",
					  data: JSON.stringify({
					  	User:user_bfr,
					  	title:this.newTodoText,
					  	ShoppingItems:[]
					  }
					  ),
					  success : function(data){
					  	lists.push({
					  		"title":data.title,
					  		"id":data.id,
					  		"User":data.User,
					  		"ShoppingItems":data.ShoppingItems
					  	})
					  	lists_old[lists_old.length] = {
					  		"title":data.title,
					  		"id":data.id,
					  		"User":data.User,
					  		"ShoppingItems":data.ShoppingItems
					  	}
					  }

					});
					/*/this.todos.push({
						
					})*/

				}
			}
		})
		let lists_vm= new Vue({
			el: '#list',
			data: {
				todo: [],
				shoppingList:"",
				listid:0,
				newTodoText:""
			},
			methods: {
				addNewTodo: function () {
					this.todo.push({
						item: this.newTodoText,
						shoppingList: this.shoppingList,
						checked:false
					})
					this.newTodoText=""
				},
				back:function(){
					$("#list").hide();
					$("#lists").show();
				},
				save:function(){
					for (var i = 0; i < this.todo.length; i++) {
						if( i < lists_old[this.listid]["ShoppingItems"].length ){
							if(this.todo[i]["checked"] != lists_old[this.listid]["ShoppingItems"][i]["checked"]  ){
								$.ajax({
								  url: '/api/shopping_items/'+this.todo[i]["id"],
								  type: 'PUT',
								  contentType : "application/json",
								  data: JSON.stringify(this.todo[i])
								});
							}
						}else{
							$.ajax({
							  url: '/api/shopping_items',
							  type: 'POST',
							  contentType : "application/json",
							  data: JSON.stringify(this.todo[i])
							});
						}
					}
				}
			}
		});


	});
});
	{% endif %}
</script>
</footer>

templates/default/includes/head.html.twig
<head>
	<title>{{page_title}} : List</title>

	<meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<style>
		body {
		  padding-top: 5rem;
		}
		.starter-template {
		  padding: 3rem 1.5rem;
		  text-align: center;
		}
		.btn_small{
		    padding: 0px 0.5em 0px 0.5em;
		}
		.spinner_containner{
			text-align:center;
		}
	</style>
</head>